In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv('train-data.csv')
df.head()

,Unnamed: 0,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
0,0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.6 km/kg,998 CC,58.16 bhp,5.0,NaN,1.75
1,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67 kmpl,1582 CC,126.2 bhp,5.0,NaN,12.50
2,2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,18.2 kmpl,1199 CC,88.7 bhp,5.0,8.61 Lakh,4.50
3,3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77 kmpl,1248 CC,88.76 bhp,7.0,NaN,6.00
4,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.2 kmpl,1968 CC,140.8 bhp,5.0,NaN,17.74

In [3]:
df.columns

Index(['Unnamed: 0', 'Name', 'Location', 'Year', 'Kilometers_Driven',
       'Fuel_Type', 'Transmission', 'Owner_Type', 'Mileage', 'Engine', 'Power',
       'Seats', 'New_Price', 'Price'],
      dtype='str')

In [4]:
df.shape

(6019, 14)

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6019 entries, 0 to 6018
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         6019 non-null   int64
 1   Name               6019 non-null   str
 2   Location           6019 non-null   str
 3   Year               6019 non-null   int64
 4   Kilometers_Driven  6019 non-null   int64
 5   Fuel_Type          6019 non-null   str
 6   Transmission       6019 non-null   str
 7   Owner_Type         6019 non-null   str
 8   Mileage            6017 non-null   str
 9   Engine             5983 non-null   str
 10  Power              5983 non-null   str
 11  Seats              5977 non-null   float64
 12  New_Price          824 non-null    str
 13  Price              6019 non-null   float64
dtypes: float64(2), int64(3), str(9)
memory usage: 658.5 KB

In [6]:
df.describe()

        Unnamed: 0         Year  Kilometers_Driven        Seats        Price
count  6019.000000  6019.000000       6.019000e+03  5977.000000  6019.000000
mean   3009.000000  2013.358199       5.873838e+04     5.278735     9.479468
std    1737.679967     3.269742       9.126884e+04     0.808840    11.187917
min       0.000000  1998.000000       1.710000e+02     0.000000     0.440000
25%    1504.500000  2011.000000       3.400000e+04     5.000000     3.500000
50%    3009.000000  2014.000000       5.300000e+04     5.000000     5.640000
75%    4513.500000  2016.000000       7.300000e+04     5.000000     9.950000
max    6018.000000  2019.000000       6.500000e+06    10.000000   160.000000

In [7]:
df.isna().sum()

Unnamed: 0              0
Name                    0
Location                0
Year                    0
Kilometers_Driven       0
Fuel_Type               0
Transmission            0
Owner_Type              0
Mileage                 2
Engine                 36
Power                  36
Seats                  42
New_Price            5195
Price                   0
dtype: int64

In [8]:
df.isna().mean()*100

Unnamed: 0            0.000000
Name                  0.000000
Location              0.000000
Year                  0.000000
Kilometers_Driven     0.000000
Fuel_Type             0.000000
Transmission          0.000000
Owner_Type            0.000000
Mileage               0.033228
Engine                0.598106
Power                 0.598106
Seats                 0.697790
New_Price            86.310018
Price                 0.000000
dtype: float64

In [9]:
df.drop(columns=['New_Price','Unnamed: 0'],inplace=True)

In [10]:
df.isna().mean()*100

Name                 0.000000
Location             0.000000
Year                 0.000000
Kilometers_Driven    0.000000
Fuel_Type            0.000000
Transmission         0.000000
Owner_Type           0.000000
Mileage              0.033228
Engine               0.598106
Power                0.598106
Seats                0.697790
Price                0.000000
dtype: float64

In [11]:
df.ffill(inplace=True)

,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,Price
0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.6 km/kg,998 CC,58.16 bhp,5.0,1.75
1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67 kmpl,1582 CC,126.2 bhp,5.0,12.50
2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,18.2 kmpl,1199 CC,88.7 bhp,5.0,4.50
3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77 kmpl,1248 CC,88.76 bhp,7.0,6.00
4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.2 kmpl,1968 CC,140.8 bhp,5.0,17.74
...,...,...,...,...,...,...,...,...,...,...,...,...
6014,Maruti Swift VDI,Delhi,2014,27365,Diesel,Manual,First,28.4 kmpl,1248 CC,74 bhp,5.0,4.75
6015,Hyundai Xcent 1.1 CRDi S,Jaipur,2015,100000,Diesel,Manual,First,24.4 kmpl,1120 CC,71 bhp,5.0,4.00
6016,Mahindra Xylo D4 BSIV,Jaipur,2012,55000,Diesel,Manual,Second,14.0 kmpl,2498 CC,112 bhp,8.0,2.90
6017,Maruti Wagon R VXI,Kolkata,2013,46000,Petrol,Manual,First,18.9 kmpl,998 CC,67.1 bhp,5.0,2.65
6018,Chevrolet Beat Diesel,Hyderabad,2011,47000,Diesel,Manual,First,25.44 kmpl,936 CC,57.6 bhp,5.0,2.50

In [12]:
df.isna().mean()*100

Name                 0.0
Location             0.0
Year                 0.0
Kilometers_Driven    0.0
Fuel_Type            0.0
Transmission         0.0
Owner_Type           0.0
Mileage              0.0
Engine               0.0
Power                0.0
Seats                0.0
Price                0.0
dtype: float64

In [13]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6019 entries, 0 to 6018
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Name               6019 non-null   str
 1   Location           6019 non-null   str
 2   Year               6019 non-null   int64
 3   Kilometers_Driven  6019 non-null   int64
 4   Fuel_Type          6019 non-null   str
 5   Transmission       6019 non-null   str
 6   Owner_Type         6019 non-null   str
 7   Mileage            6019 non-null   str
 8   Engine             6019 non-null   str
 9   Power              6019 non-null   str
 10  Seats              6019 non-null   float64
 11  Price              6019 non-null   float64
dtypes: float64(2), int64(2), str(8)
memory usage: 564.4 KB

In [14]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(sparse_output=False)
data = ohe.fit_transform(df[['Location']])
df1 = pd.DataFrame(data,columns=ohe.get_feature_names_out())

In [15]:
df1

,Location_Ahmedabad,Location_Bangalore,Location_Chennai,Location_Coimbatore,Location_Delhi,Location_Hyderabad,Location_Jaipur,Location_Kochi,Location_Kolkata,Location_Mumbai,Location_Pune
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
6014,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
6015,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
6016,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
6017,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
6018,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0

In [16]:
ohe1 = OneHotEncoder(sparse_output=False)
data1 = ohe1.fit_transform(df[['Fuel_Type']])
df2 = pd.DataFrame(data1,columns=ohe1.get_feature_names_out())

In [17]:
df2

,Fuel_Type_CNG,Fuel_Type_Diesel,Fuel_Type_Electric,Fuel_Type_LPG,Fuel_Type_Petrol
0,1.0,0.0,0.0,0.0,0.0
1,0.0,1.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,1.0
3,0.0,1.0,0.0,0.0,0.0
4,0.0,1.0,0.0,0.0,0.0
...,...,...,...,...,...
6014,0.0,1.0,0.0,0.0,0.0
6015,0.0,1.0,0.0,0.0,0.0
6016,0.0,1.0,0.0,0.0,0.0
6017,0.0,0.0,0.0,0.0,1.0
6018,0.0,1.0,0.0,0.0,0.0

In [18]:
ohe2=OneHotEncoder(sparse_output=False)
data2 = ohe2.fit_transform(df[['Transmission']])
df3 = pd.DataFrame(data2,columns=ohe2.get_feature_names_out())

In [19]:
df3

      Transmission_Automatic  Transmission_Manual
0                        0.0                  1.0
1                        0.0                  1.0
2                        0.0                  1.0
3                        0.0                  1.0
4                        1.0                  0.0
...                      ...                  ...
6014                     0.0                  1.0
6015                     0.0                  1.0
6016                     0.0                  1.0
6017                     0.0                  1.0
6018                     0.0                  1.0

[6019 rows x 2 columns]

In [20]:
df

,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,Price
0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.6 km/kg,998 CC,58.16 bhp,5.0,1.75
1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67 kmpl,1582 CC,126.2 bhp,5.0,12.50
2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,18.2 kmpl,1199 CC,88.7 bhp,5.0,4.50
3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77 kmpl,1248 CC,88.76 bhp,7.0,6.00
4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.2 kmpl,1968 CC,140.8 bhp,5.0,17.74
...,...,...,...,...,...,...,...,...,...,...,...,...
6014,Maruti Swift VDI,Delhi,2014,27365,Diesel,Manual,First,28.4 kmpl,1248 CC,74 bhp,5.0,4.75
6015,Hyundai Xcent 1.1 CRDi S,Jaipur,2015,100000,Diesel,Manual,First,24.4 kmpl,1120 CC,71 bhp,5.0,4.00
6016,Mahindra Xylo D4 BSIV,Jaipur,2012,55000,Diesel,Manual,Second,14.0 kmpl,2498 CC,112 bhp,8.0,2.90
6017,Maruti Wagon R VXI,Kolkata,2013,46000,Petrol,Manual,First,18.9 kmpl,998 CC,67.1 bhp,5.0,2.65
6018,Chevrolet Beat Diesel,Hyderabad,2011,47000,Diesel,Manual,First,25.44 kmpl,936 CC,57.6 bhp,5.0,2.50

In [21]:
df = pd.concat([df,df1,df2,df3],axis=1)

In [22]:
df.head()

,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,...,Location_Kolkata,Location_Mumbai,Location_Pune,Fuel_Type_CNG,Fuel_Type_Diesel,Fuel_Type_Electric,Fuel_Type_LPG,Fuel_Type_Petrol,Transmission_Automatic,Transmission_Manual
0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.6 km/kg,998 CC,58.16 bhp,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67 kmpl,1582 CC,126.2 bhp,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,18.2 kmpl,1199 CC,88.7 bhp,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77 kmpl,1248 CC,88.76 bhp,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.2 kmpl,1968 CC,140.8 bhp,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0

In [23]:
df.drop(['Location','Fuel_Type','Transmission'],axis=1,inplace=True)

In [24]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6019 entries, 0 to 6018
Data columns (total 27 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Name                    6019 non-null   str
 1   Year                    6019 non-null   int64
 2   Kilometers_Driven       6019 non-null   int64
 3   Owner_Type              6019 non-null   str
 4   Mileage                 6019 non-null   str
 5   Engine                  6019 non-null   str
 6   Power                   6019 non-null   str
 7   Seats                   6019 non-null   float64
 8   Price                   6019 non-null   float64
 9   Location_Ahmedabad      6019 non-null   float64
 10  Location_Bangalore      6019 non-null   float64
 11  Location_Chennai        6019 non-null   float64
 12  Location_Coimbatore     6019 non-null   float64
 13  Location_Delhi          6019 non-null   float64
 14  Location_Hyderabad      6019 non-null   float64
 15  Location_Jaipur         6019 non-null   float64
 16  Location_Kochi          6019 non-null   float64
 17  Location_Kolkata        6019 non-null   float64
 18  Location_Mumbai         6019 non-null   float64
 19  Location_Pune           6019 non-null   float64
 20  Fuel_Type_CNG           6019 non-null   float64
 21  Fuel_Type_Diesel        6019 non-null   float64
 22  Fuel_Type_Electric      6019 non-null   float64
 23  Fuel_Type_LPG           6019 non-null   float64
 24  Fuel_Type_Petrol        6019 non-null   float64
 25  Transmission_Automatic  6019 non-null   float64
 26  Transmission_Manual     6019 non-null   float64
dtypes: float64(20), int64(2), str(5)
memory usage: 1.2 MB

In [25]:
df['Owner_Type'].unique()

<StringArray>
['First', 'Second', 'Fourth & Above', 'Third']
Length: 4, dtype: str

In [26]:
df['Owner_Type'].value_counts()

Owner_Type
First             4929
Second             968
Third              113
Fourth & Above       9
Name: count, dtype: int64

In [27]:
df['Owner_Type']=df['Owner_Type'].replace({'First':0, 'Second':1, 'Fourth & Above':3, 'Third':2})
df['Owner_Type']=df['Owner_Type'].astype(int)

In [28]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6019 entries, 0 to 6018
Data columns (total 27 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Name                    6019 non-null   str
 1   Year                    6019 non-null   int64
 2   Kilometers_Driven       6019 non-null   int64
 3   Owner_Type              6019 non-null   int64
 4   Mileage                 6019 non-null   str
 5   Engine                  6019 non-null   str
 6   Power                   6019 non-null   str
 7   Seats                   6019 non-null   float64
 8   Price                   6019 non-null   float64
 9   Location_Ahmedabad      6019 non-null   float64
 10  Location_Bangalore      6019 non-null   float64
 11  Location_Chennai        6019 non-null   float64
 12  Location_Coimbatore     6019 non-null   float64
 13  Location_Delhi          6019 non-null   float64
 14  Location_Hyderabad      6019 non-null   float64
 15  Location_Jaipur         6019 non-null   float64
 16  Location_Kochi          6019 non-null   float64
 17  Location_Kolkata        6019 non-null   float64
 18  Location_Mumbai         6019 non-null   float64
 19  Location_Pune           6019 non-null   float64
 20  Fuel_Type_CNG           6019 non-null   float64
 21  Fuel_Type_Diesel        6019 non-null   float64
 22  Fuel_Type_Electric      6019 non-null   float64
 23  Fuel_Type_LPG           6019 non-null   float64
 24  Fuel_Type_Petrol        6019 non-null   float64
 25  Transmission_Automatic  6019 non-null   float64
 26  Transmission_Manual     6019 non-null   float64
dtypes: float64(20), int64(3), str(4)
memory usage: 1.2 MB

In [29]:
df['Power'].unique()

<StringArray>
[ '58.16 bhp',  '126.2 bhp',   '88.7 bhp',  '88.76 bhp',  '140.8 bhp',
   '55.2 bhp',   '63.1 bhp',  '171.5 bhp',  '103.6 bhp',     '74 bhp',
 ...
    '382 bhp',  '74.96 bhp',    '552 bhp',    '127 bhp',    '560 bhp',
  '116.4 bhp',  '161.6 bhp',  '488.1 bhp',    '103 bhp', '181.04 bhp']
Length: 372, dtype: str

In [30]:
df['Power'].value_counts()

Power
74 bhp        237
98.6 bhp      131
73.9 bhp      126
140 bhp       123
78.9 bhp      112
             ...
116.4 bhp       1
161.6 bhp       1
488.1 bhp       1
103 bhp         1
181.04 bhp      1
Name: count, Length: 372, dtype: int64

In [31]:
df['Engine'].unique()

<StringArray>
[ '998 CC', '1582 CC', '1199 CC', '1248 CC', '1968 CC',  '814 CC', '1461 CC',
 '2755 CC', '1598 CC', '1462 CC',
 ...
  '970 CC', '2925 CC', '2200 CC', '5000 CC', '2149 CC', '5998 CC', '2092 CC',
 '5204 CC', '2112 CC', '1797 CC']
Length: 146, dtype: str

In [32]:
df['Engine'] = df['Engine'].replace({'CC' :''},regex=True)
df['Engine'] = df['Engine'].astype(int)

In [33]:
for i in df['Power'].unique():
    if not i.endswith('bhp'):
      print(i)

In [34]:
df['Power'] = df['Power'].replace({'bhp' :''},regex=True)

In [35]:
df['Power'] = df['Power'].str.strip()

In [36]:
import re
for i in df['Power'].unique():
    if not re.match(r'^[0-9,]+$',i):
        print(i)

58.16
126.2
88.7
88.76
140.8
55.2
63.1
171.5
103.6
103.25
116.3
187.7
175.56
98.6
83.8
167.62
88.5
177.01
67.1
108.45
138.1
179.5
103.5
254.8
73.9
46.3
37.5
82.9
149.92
138.03
112.2
163.7
174.33
103.2
53.3
78.9
147.6
147.8
108.5
86.8
187.74
null
86.7
73.94
117.3
168.5
89.84
82.85
241.4
270.9
126.32
100.6
75.94
107.3
37.48
91.1
85.80
362.07
121.3
81.80
76.8
103.52
362.9
67.06
120.7
81.86
88.73
57.6
157.75
102.5
201.1
83.1
68.05
88.50
81.83
64.1
177.5
246.7
177.46
67.04
189.08
53.5
194.3
254.79
66.1
123.24
47.3
88.8
201.15
93.7
177.6
141.1
83.14
67.05
87.2
246.74
98.79
62.1
174.3
335.2
191.34
108.49
138.02
187.4
103.3
164.7
79.4
198.5
73.8
181.43
85.8
207.8
108.4
82.5
364.9
107.2
113.98
126.3
237.4
99.6
66.7
98.59
92.7
147.51
197.2
167.6
110.4
73.97
147.9
116.6
34.2
108.62
118.3
38.4
241.38
153.86
163.5
226.6
84.8
53.64
158.2
69.01
181.03
58.2
104.68
126.24
73.75
130.2
57.5
97.7
121.4
98.96
174.5
121.36
91.72
65.3
88.2
35.5
86.79
157.7
40.3
91.7
114.4
158.8
157.8
123.7
56.3
270.88
167.7
148.31
80.46
138.08
74.9
91.2
102.57
97.6
102.53
112.4
73.74
108.495
116.9
70.02
261.49
105.5
168.7
55.23
94.68
152.88
163.2
203.2
271.23
63.12
85.7
308.43
118.6
199.3
83.83
262.6
58.33
86.76
76.9
174.57
301.73
68.1
394.3
80.9
147.5
120.33
82.4
231.1
335.3
198.25
224.34
71.01
271.72
135.1
64.08
261.5
123.37
175.67
110.5
178.4
193.1
48.21
89.75
387.3
130.3
281.61
52.8
139.01
98.82
139.07
83.11
74.93
74.96
116.4
161.6
488.1
181.04

In [37]:
# import re
# for i in df['Power'].unique():
#     if not re.match(r'',i):
#         print(i)

In [38]:
df['Power'] =  df['Power'].replace({'null':0})
df['Power'] = df['Power'].astype(float)

In [39]:
df['Mileage'].unique()

<StringArray>
[ '26.6 km/kg',  '19.67 kmpl',   '18.2 kmpl',  '20.77 kmpl',   '15.2 kmpl',
  '21.1 km/kg',  '23.08 kmpl',  '11.36 kmpl',  '20.54 kmpl',   '22.3 kmpl',
 ...
   '9.74 kmpl',  '14.81 kmpl',    '8.2 kmpl',  '12.97 kmpl',    '7.5 kmpl',
 '30.46 km/kg',    '6.4 kmpl',  '12.85 kmpl',  '18.69 kmpl',  '17.24 kmpl']
Length: 442, dtype: str

In [40]:
for i in df['Mileage'].unique():
    if not i.endswith('km/kg') and not i.endswith('kmpl'):
      print(i)

In [41]:
def conv_Mileage(row):
    row = row.lower().strip()
    if row.endswith('km/kg'):
        num = row.replace('km/kg','')
        return float(num)*1.4
    elif row.endswith('kmpl'):
         num = row.replace('kmpl','')
         return float(num)
        
df['Mileage'] = df['Mileage'].apply(conv_Mileage)

In [42]:
df.head()

,Name,Year,Kilometers_Driven,Owner_Type,Mileage,Engine,Power,Seats,Price,Location_Ahmedabad,...,Location_Kolkata,Location_Mumbai,Location_Pune,Fuel_Type_CNG,Fuel_Type_Diesel,Fuel_Type_Electric,Fuel_Type_LPG,Fuel_Type_Petrol,Transmission_Automatic,Transmission_Manual
0,Maruti Wagon R LXI CNG,2010,72000,0,37.24,998,58.16,5.0,1.75,0.0,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
1,Hyundai Creta 1.6 CRDi SX Option,2015,41000,0,19.67,1582,126.20,5.0,12.50,0.0,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
2,Honda Jazz V,2011,46000,0,18.20,1199,88.70,5.0,4.50,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
3,Maruti Ertiga VDI,2012,87000,0,20.77,1248,88.76,7.0,6.00,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
4,Audi A4 New 2.0 TDI Multitronic,2013,40670,1,15.20,1968,140.80,5.0,17.74,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0

In [43]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6019 entries, 0 to 6018
Data columns (total 27 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Name                    6019 non-null   str
 1   Year                    6019 non-null   int64
 2   Kilometers_Driven       6019 non-null   int64
 3   Owner_Type              6019 non-null   int64
 4   Mileage                 6019 non-null   float64
 5   Engine                  6019 non-null   int64
 6   Power                   6019 non-null   float64
 7   Seats                   6019 non-null   float64
 8   Price                   6019 non-null   float64
 9   Location_Ahmedabad      6019 non-null   float64
 10  Location_Bangalore      6019 non-null   float64
 11  Location_Chennai        6019 non-null   float64
 12  Location_Coimbatore     6019 non-null   float64
 13  Location_Delhi          6019 non-null   float64
 14  Location_Hyderabad      6019 non-null   float64
 15  Location_Jaipur         6019 non-null   float64
 16  Location_Kochi          6019 non-null   float64
 17  Location_Kolkata        6019 non-null   float64
 18  Location_Mumbai         6019 non-null   float64
 19  Location_Pune           6019 non-null   float64
 20  Fuel_Type_CNG           6019 non-null   float64
 21  Fuel_Type_Diesel        6019 non-null   float64
 22  Fuel_Type_Electric      6019 non-null   float64
 23  Fuel_Type_LPG           6019 non-null   float64
 24  Fuel_Type_Petrol        6019 non-null   float64
 25  Transmission_Automatic  6019 non-null   float64
 26  Transmission_Manual     6019 non-null   float64
dtypes: float64(22), int64(4), str(1)
memory usage: 1.2 MB

In [44]:
df['Power']=df['Power'].replace({0:np.nan})

In [45]:
df.isna().sum()

Name                        0
Year                        0
Kilometers_Driven           0
Owner_Type                  0
Mileage                     0
Engine                      0
Power                     108
Seats                       0
Price                       0
Location_Ahmedabad          0
Location_Bangalore          0
Location_Chennai            0
Location_Coimbatore         0
Location_Delhi              0
Location_Hyderabad          0
Location_Jaipur             0
Location_Kochi              0
Location_Kolkata            0
Location_Mumbai             0
Location_Pune               0
Fuel_Type_CNG               0
Fuel_Type_Diesel            0
Fuel_Type_Electric          0
Fuel_Type_LPG               0
Fuel_Type_Petrol            0
Transmission_Automatic      0
Transmission_Manual         0
dtype: int64

In [46]:
df.ffill(inplace=True)
df.head(3)

,Name,Year,Kilometers_Driven,Owner_Type,Mileage,Engine,Power,Seats,Price,Location_Ahmedabad,...,Location_Kolkata,Location_Mumbai,Location_Pune,Fuel_Type_CNG,Fuel_Type_Diesel,Fuel_Type_Electric,Fuel_Type_LPG,Fuel_Type_Petrol,Transmission_Automatic,Transmission_Manual
0,Maruti Wagon R LXI CNG,2010,72000,0,37.24,998,58.16,5.0,1.75,0.0,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
1,Hyundai Creta 1.6 CRDi SX Option,2015,41000,0,19.67,1582,126.20,5.0,12.50,0.0,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
2,Honda Jazz V,2011,46000,0,18.20,1199,88.70,5.0,4.50,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0

In [47]:
df.isna().sum()

Name                      0
Year                      0
Kilometers_Driven         0
Owner_Type                0
Mileage                   0
Engine                    0
Power                     0
Seats                     0
Price                     0
Location_Ahmedabad        0
Location_Bangalore        0
Location_Chennai          0
Location_Coimbatore       0
Location_Delhi            0
Location_Hyderabad        0
Location_Jaipur           0
Location_Kochi            0
Location_Kolkata          0
Location_Mumbai           0
Location_Pune             0
Fuel_Type_CNG             0
Fuel_Type_Diesel          0
Fuel_Type_Electric        0
Fuel_Type_LPG             0
Fuel_Type_Petrol          0
Transmission_Automatic    0
Transmission_Manual       0
dtype: int64

In [48]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6019 entries, 0 to 6018
Data columns (total 27 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Name                    6019 non-null   str
 1   Year                    6019 non-null   int64
 2   Kilometers_Driven       6019 non-null   int64
 3   Owner_Type              6019 non-null   int64
 4   Mileage                 6019 non-null   float64
 5   Engine                  6019 non-null   int64
 6   Power                   6019 non-null   float64
 7   Seats                   6019 non-null   float64
 8   Price                   6019 non-null   float64
 9   Location_Ahmedabad      6019 non-null   float64
 10  Location_Bangalore      6019 non-null   float64
 11  Location_Chennai        6019 non-null   float64
 12  Location_Coimbatore     6019 non-null   float64
 13  Location_Delhi          6019 non-null   float64
 14  Location_Hyderabad      6019 non-null   float64
 15  Location_Jaipur         6019 non-null   float64
 16  Location_Kochi          6019 non-null   float64
 17  Location_Kolkata        6019 non-null   float64
 18  Location_Mumbai         6019 non-null   float64
 19  Location_Pune           6019 non-null   float64
 20  Fuel_Type_CNG           6019 non-null   float64
 21  Fuel_Type_Diesel        6019 non-null   float64
 22  Fuel_Type_Electric      6019 non-null   float64
 23  Fuel_Type_LPG           6019 non-null   float64
 24  Fuel_Type_Petrol        6019 non-null   float64
 25  Transmission_Automatic  6019 non-null   float64
 26  Transmission_Manual     6019 non-null   float64
dtypes: float64(22), int64(4), str(1)
memory usage: 1.2 MB

In [49]:
x=df.drop(['Price'],axis=1)
y=df['Price']

In [50]:
pip install category encoders

Requirement already satisfied: category in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (0.0.3)
Requirement already satisfied: encoders in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (0.0.4)
Requirement already satisfied: numpy in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from category) (2.4.2)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.0 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [51]:
import category_encoders as ce
te = ce.TargetEncoder(cols=['Name'])
df = te.fit_transform(x,y)

In [52]:
df.head()

,Name,Year,Kilometers_Driven,Owner_Type,Mileage,Engine,Power,Seats,Location_Ahmedabad,Location_Bangalore,...,Location_Kolkata,Location_Mumbai,Location_Pune,Fuel_Type_CNG,Fuel_Type_Diesel,Fuel_Type_Electric,Fuel_Type_LPG,Fuel_Type_Petrol,Transmission_Automatic,Transmission_Manual
0,6.601896,2010,72000,0,37.24,998,58.16,5.0,0.0,0.0,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
1,10.376382,2015,41000,0,19.67,1582,126.20,5.0,0.0,0.0,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
2,8.873984,2011,46000,0,18.20,1199,88.70,5.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
3,7.882818,2012,87000,0,20.77,1248,88.76,7.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
4,10.135233,2013,40670,1,15.20,1968,140.80,5.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0

In [53]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6019 entries, 0 to 6018
Data columns (total 26 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Name                    6019 non-null   float64
 1   Year                    6019 non-null   int64
 2   Kilometers_Driven       6019 non-null   int64
 3   Owner_Type              6019 non-null   int64
 4   Mileage                 6019 non-null   float64
 5   Engine                  6019 non-null   int64
 6   Power                   6019 non-null   float64
 7   Seats                   6019 non-null   float64
 8   Location_Ahmedabad      6019 non-null   float64
 9   Location_Bangalore      6019 non-null   float64
 10  Location_Chennai        6019 non-null   float64
 11  Location_Coimbatore     6019 non-null   float64
 12  Location_Delhi          6019 non-null   float64
 13  Location_Hyderabad      6019 non-null   float64
 14  Location_Jaipur         6019 non-null   float64
 15  Location_Kochi          6019 non-null   float64
 16  Location_Kolkata        6019 non-null   float64
 17  Location_Mumbai         6019 non-null   float64
 18  Location_Pune           6019 non-null   float64
 19  Fuel_Type_CNG           6019 non-null   float64
 20  Fuel_Type_Diesel        6019 non-null   float64
 21  Fuel_Type_Electric      6019 non-null   float64
 22  Fuel_Type_LPG           6019 non-null   float64
 23  Fuel_Type_Petrol        6019 non-null   float64
 24  Transmission_Automatic  6019 non-null   float64
 25  Transmission_Manual     6019 non-null   float64
dtypes: float64(22), int64(4)
memory usage: 1.2 MB

In [54]:
x.shape

(6019, 26)

In [55]:
x

,Name,Year,Kilometers_Driven,Owner_Type,Mileage,Engine,Power,Seats,Location_Ahmedabad,Location_Bangalore,...,Location_Kolkata,Location_Mumbai,Location_Pune,Fuel_Type_CNG,Fuel_Type_Diesel,Fuel_Type_Electric,Fuel_Type_LPG,Fuel_Type_Petrol,Transmission_Automatic,Transmission_Manual
0,Maruti Wagon R LXI CNG,2010,72000,0,37.24,998,58.16,5.0,0.0,0.0,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
1,Hyundai Creta 1.6 CRDi SX Option,2015,41000,0,19.67,1582,126.20,5.0,0.0,0.0,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
2,Honda Jazz V,2011,46000,0,18.20,1199,88.70,5.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
3,Maruti Ertiga VDI,2012,87000,0,20.77,1248,88.76,7.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
4,Audi A4 New 2.0 TDI Multitronic,2013,40670,1,15.20,1968,140.80,5.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6014,Maruti Swift VDI,2014,27365,0,28.40,1248,74.00,5.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
6015,Hyundai Xcent 1.1 CRDi S,2015,100000,0,24.40,1120,71.00,5.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
6016,Mahindra Xylo D4 BSIV,2012,55000,1,14.00,2498,112.00,8.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
6017,Maruti Wagon R VXI,2013,46000,0,18.90,998,67.10,5.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
6018,Chevrolet Beat Diesel,2011,47000,0,25.44,936,57.60,5.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0

In [56]:
y

0        1.75
1       12.50
2        4.50
3        6.00
4       17.74
        ...
6014     4.75
6015     4.00
6016     2.90
6017     2.65
6018     2.50
Name: Price, Length: 6019, dtype: float64

In [57]:
df

,Name,Year,Kilometers_Driven,Owner_Type,Mileage,Engine,Power,Seats,Location_Ahmedabad,Location_Bangalore,...,Location_Kolkata,Location_Mumbai,Location_Pune,Fuel_Type_CNG,Fuel_Type_Diesel,Fuel_Type_Electric,Fuel_Type_LPG,Fuel_Type_Petrol,Transmission_Automatic,Transmission_Manual
0,6.601896,2010,72000,0,37.24,998,58.16,5.0,0.0,0.0,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
1,10.376382,2015,41000,0,19.67,1582,126.20,5.0,0.0,0.0,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
2,8.873984,2011,46000,0,18.20,1199,88.70,5.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
3,7.882818,2012,87000,0,20.77,1248,88.76,7.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
4,10.135233,2013,40670,1,15.20,1968,140.80,5.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6014,5.185781,2014,27365,0,28.40,1248,74.00,5.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
6015,8.474989,2015,100000,0,24.40,1120,71.00,5.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
6016,8.623424,2012,55000,1,14.00,2498,112.00,8.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
6017,5.884263,2013,46000,0,18.90,998,67.10,5.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
6018,8.399838,2011,47000,0,25.44,936,57.60,5.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0

In [58]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest = train_test_split(df,y,test_size=0.2,random_state=42)

In [59]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(xtrain,ytrain)

LinearRegression()

In [60]:
ypred=model.predict(xtest)

In [61]:
ypred

array([-0.18956595, 11.81184847,  7.71920979, ...,  7.67433076,
        8.59379969,  3.22476245], shape=(1204,))

In [62]:
from sklearn.metrics import r2_score
print("r2 score :",r2_score(ytest,ypred))

r2 score : 0.6935815695783552

r2_score = 1 - ss_res/ss_tot

ss_res = sum(ypred - yact) 

ss_total = the total variance of the actual target values
  =sum(yact - mean of all actual values)

In [63]:
print("slope",model.coef_)
print("y_intercept",model.intercept_)

slope [ 3.00445622e+00  4.23501100e-01 -1.73505102e-05 -3.15867605e-01
  7.04302256e-03  3.67828121e-04  5.87982324e-02 -8.10528259e-01
 -5.25608938e-01  9.02292467e-01  8.72008966e-02  1.14763813e+00
 -4.55837644e-01  1.24683284e+00  3.52174279e-01 -3.32376312e-01
 -9.06155241e-01 -1.26159898e+00 -2.54561497e-01 -1.40634717e-01
 -4.47048482e-01  3.87358365e+00 -2.25857107e+00 -1.02732938e+00
 -5.71494161e-02  5.71494160e-02]
y_intercept -872.1441295507789

In [64]:
ytrain_pred = model.predict(xtrain)

In [65]:
ytrain_pred

array([ 0.15317742,  9.64344564, 11.24480352, ...,  7.74558401,
        0.04400009,  3.71596373], shape=(4815,))

In [66]:
from sklearn.metrics import r2_score
print("r2_score:",r2_score(ytrain,ytrain_pred))

r2_score: 0.8248777616396096

In [67]:
r2_score(ytest,ypred)

0.6935815695783552

In [68]:
if r2_score(ytrain,ytrain_pred)<.60:
    print("overfit")

elif r2_score(ytrain_pred,ytrain) > r2_score(ytest,ypred)+.11:
    print("underfit")

else:
    print("good fit")

good fit

In [69]:
from sklearn.metrics import mean_absolute_error,mean_squared_error,root_mean_squared_error

In [70]:
mse=mean_squared_error(ytest,ypred)
mse

37.70769635440941

In [71]:
mean_absolute_error(ytest,ypred)

3.3066654942790086

In [72]:
root_mean_squared_error(ytest,ypred)

6.1406592768537

In [97]:
from sklearn.model_selection import cross_val_score
score = cross_val_score(model,df,y,cv=5,scoring='r2')

In [98]:
score

array([0.80876433, 0.71864692, 0.82351707, 0.80843718, 0.83685224])

In [99]:
score.mean()

np.float64(0.7992435473850188)

In [100]:
score.std()

np.float64(0.04165237665088037)

In [73]:
df.head(1)

,Name,Year,Kilometers_Driven,Owner_Type,Mileage,Engine,Power,Seats,Location_Ahmedabad,Location_Bangalore,...,Location_Kolkata,Location_Mumbai,Location_Pune,Fuel_Type_CNG,Fuel_Type_Diesel,Fuel_Type_Electric,Fuel_Type_LPG,Fuel_Type_Petrol,Transmission_Automatic,Transmission_Manual
0,6.601896,2010,72000,0,37.24,998,58.16,5.0,0.0,0.0,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0

Name	Location	Year	Kilometers_Driven	Fuel_Type	Transmission	Owner_Type	Mileage	Engine	Power	Seats	New_Price	Price


Maruti Wagon R LXI CNG	Mumbai	2010	72000	CNG	Manual	First	26.6 km/kg	998 CC	58.16 bhp	5.0	NaN	1.75

In [74]:
Name = input("Enter Name:")
Location = input('Enter Location:')
Year = int(input("Enter year:"))
Kilometers_Driven = int(input("Enter Kilometers:"))
Fuel_Type = input("Enter Fuel Type:")
Transmission = input("Enter Transmission")

In [75]:
Owner_Type = int(input("Enter Owner Type:"))
Mileage = input('Enter Mileage:')
Engine = input('Enter Engine:')
Power = input('Enter Power:')
Seats = int(input('Enter seats:'))

In [76]:
data = {
    "Name":[Name],
    "Location":[Location],
    "Year":[Year],
    "Kilometers_Driven":[Kilometers_Driven],
    "Fuel_Type":[Fuel_Type],
    "Transmission":[Transmission],
    "Owner_Type":[Owner_Type],
    "Mileage":[Mileage],
    "Engine":[Engine],
    "Power":[Power],
    "Seats":[Seats]
}

In [77]:
df1=pd.DataFrame(data)
df1

,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats
0,Honda Jazz V,Mumbai,2012,56000,Petrol,Manual,2,20.8 kmpl,900 CC,56.53 bhp,5

In [78]:
data1=ohe.transform(df1[['Location']])
df2=pd.DataFrame(data1,columns=ohe.get_feature_names_out())

In [79]:
data2=ohe1.transform(df1[['Fuel_Type']])
df3=pd.DataFrame(data2,columns=ohe1.get_feature_names_out())

In [80]:
data3=ohe2.transform(df1[['Transmission']])
df4=pd.DataFrame(data3,columns=ohe2.get_feature_names_out())

In [81]:
df1

,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats
0,Honda Jazz V,Mumbai,2012,56000,Petrol,Manual,2,20.8 kmpl,900 CC,56.53 bhp,5

In [82]:
df1=pd.concat([df1,df2,df3,df4],axis=1)
df1

,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,...,Location_Kolkata,Location_Mumbai,Location_Pune,Fuel_Type_CNG,Fuel_Type_Diesel,Fuel_Type_Electric,Fuel_Type_LPG,Fuel_Type_Petrol,Transmission_Automatic,Transmission_Manual
0,Honda Jazz V,Mumbai,2012,56000,Petrol,Manual,2,20.8 kmpl,900 CC,56.53 bhp,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0

In [83]:
df1.drop(['Location','Fuel_Type','Transmission'],axis=1,inplace=True)

In [84]:
df1

,Name,Year,Kilometers_Driven,Owner_Type,Mileage,Engine,Power,Seats,Location_Ahmedabad,Location_Bangalore,...,Location_Kolkata,Location_Mumbai,Location_Pune,Fuel_Type_CNG,Fuel_Type_Diesel,Fuel_Type_Electric,Fuel_Type_LPG,Fuel_Type_Petrol,Transmission_Automatic,Transmission_Manual
0,Honda Jazz V,2012,56000,2,20.8 kmpl,900 CC,56.53 bhp,5,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0

In [85]:
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 26 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Name                    1 non-null      str
 1   Year                    1 non-null      int64
 2   Kilometers_Driven       1 non-null      int64
 3   Owner_Type              1 non-null      int64
 4   Mileage                 1 non-null      str
 5   Engine                  1 non-null      str
 6   Power                   1 non-null      str
 7   Seats                   1 non-null      int64
 8   Location_Ahmedabad      1 non-null      float64
 9   Location_Bangalore      1 non-null      float64
 10  Location_Chennai        1 non-null      float64
 11  Location_Coimbatore     1 non-null      float64
 12  Location_Delhi          1 non-null      float64
 13  Location_Hyderabad      1 non-null      float64
 14  Location_Jaipur         1 non-null      float64
 15  Location_Kochi          1 non-null      float64
 16  Location_Kolkata        1 non-null      float64
 17  Location_Mumbai         1 non-null      float64
 18  Location_Pune           1 non-null      float64
 19  Fuel_Type_CNG           1 non-null      float64
 20  Fuel_Type_Diesel        1 non-null      float64
 21  Fuel_Type_Electric      1 non-null      float64
 22  Fuel_Type_LPG           1 non-null      float64
 23  Fuel_Type_Petrol        1 non-null      float64
 24  Transmission_Automatic  1 non-null      float64
 25  Transmission_Manual     1 non-null      float64
dtypes: float64(18), int64(4), str(4)
memory usage: 340.0 bytes

In [86]:
def conv_Mileage(row):
    row = row.lower().strip()
    if row.endswith('km/kg'):
        num = row.replace('km/kg','')
        return float(num)*1.4
    elif row.endswith('kmpl'):
         num = row.replace('kmpl','')
         return float(num)
        
df1['Mileage'] = df1['Mileage'].apply(conv_Mileage)

In [87]:
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 26 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Name                    1 non-null      str
 1   Year                    1 non-null      int64
 2   Kilometers_Driven       1 non-null      int64
 3   Owner_Type              1 non-null      int64
 4   Mileage                 1 non-null      float64
 5   Engine                  1 non-null      str
 6   Power                   1 non-null      str
 7   Seats                   1 non-null      int64
 8   Location_Ahmedabad      1 non-null      float64
 9   Location_Bangalore      1 non-null      float64
 10  Location_Chennai        1 non-null      float64
 11  Location_Coimbatore     1 non-null      float64
 12  Location_Delhi          1 non-null      float64
 13  Location_Hyderabad      1 non-null      float64
 14  Location_Jaipur         1 non-null      float64
 15  Location_Kochi          1 non-null      float64
 16  Location_Kolkata        1 non-null      float64
 17  Location_Mumbai         1 non-null      float64
 18  Location_Pune           1 non-null      float64
 19  Fuel_Type_CNG           1 non-null      float64
 20  Fuel_Type_Diesel        1 non-null      float64
 21  Fuel_Type_Electric      1 non-null      float64
 22  Fuel_Type_LPG           1 non-null      float64
 23  Fuel_Type_Petrol        1 non-null      float64
 24  Transmission_Automatic  1 non-null      float64
 25  Transmission_Manual     1 non-null      float64
dtypes: float64(19), int64(4), str(3)
memory usage: 340.0 bytes

In [88]:
df1['Engine'] = df1['Engine'].replace({'CC' :''},regex=True)
df1['Engine'] = df1['Engine'].astype(int)

In [89]:
df1['Power'] = df1['Power'].replace({'bhp' :''},regex=True)
df1['Power'] = df1['Power'].astype(float)

In [90]:
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 26 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Name                    1 non-null      str
 1   Year                    1 non-null      int64
 2   Kilometers_Driven       1 non-null      int64
 3   Owner_Type              1 non-null      int64
 4   Mileage                 1 non-null      float64
 5   Engine                  1 non-null      int64
 6   Power                   1 non-null      float64
 7   Seats                   1 non-null      int64
 8   Location_Ahmedabad      1 non-null      float64
 9   Location_Bangalore      1 non-null      float64
 10  Location_Chennai        1 non-null      float64
 11  Location_Coimbatore     1 non-null      float64
 12  Location_Delhi          1 non-null      float64
 13  Location_Hyderabad      1 non-null      float64
 14  Location_Jaipur         1 non-null      float64
 15  Location_Kochi          1 non-null      float64
 16  Location_Kolkata        1 non-null      float64
 17  Location_Mumbai         1 non-null      float64
 18  Location_Pune           1 non-null      float64
 19  Fuel_Type_CNG           1 non-null      float64
 20  Fuel_Type_Diesel        1 non-null      float64
 21  Fuel_Type_Electric      1 non-null      float64
 22  Fuel_Type_LPG           1 non-null      float64
 23  Fuel_Type_Petrol        1 non-null      float64
 24  Transmission_Automatic  1 non-null      float64
 25  Transmission_Manual     1 non-null      float64
dtypes: float64(20), int64(5), str(1)
memory usage: 340.0 bytes

In [91]:
df1['Engine']

0    900
Name: Engine, dtype: int64

In [92]:
df1=te.transform(df1)

In [93]:
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 26 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Name                    1 non-null      float64
 1   Year                    1 non-null      int64
 2   Kilometers_Driven       1 non-null      int64
 3   Owner_Type              1 non-null      int64
 4   Mileage                 1 non-null      float64
 5   Engine                  1 non-null      int64
 6   Power                   1 non-null      float64
 7   Seats                   1 non-null      int64
 8   Location_Ahmedabad      1 non-null      float64
 9   Location_Bangalore      1 non-null      float64
 10  Location_Chennai        1 non-null      float64
 11  Location_Coimbatore     1 non-null      float64
 12  Location_Delhi          1 non-null      float64
 13  Location_Hyderabad      1 non-null      float64
 14  Location_Jaipur         1 non-null      float64
 15  Location_Kochi          1 non-null      float64
 16  Location_Kolkata        1 non-null      float64
 17  Location_Mumbai         1 non-null      float64
 18  Location_Pune           1 non-null      float64
 19  Fuel_Type_CNG           1 non-null      float64
 20  Fuel_Type_Diesel        1 non-null      float64
 21  Fuel_Type_Electric      1 non-null      float64
 22  Fuel_Type_LPG           1 non-null      float64
 23  Fuel_Type_Petrol        1 non-null      float64
 24  Transmission_Automatic  1 non-null      float64
 25  Transmission_Manual     1 non-null      float64
dtypes: float64(21), int64(5)
memory usage: 340.0 bytes

In [94]:
df1

,Name,Year,Kilometers_Driven,Owner_Type,Mileage,Engine,Power,Seats,Location_Ahmedabad,Location_Bangalore,...,Location_Kolkata,Location_Mumbai,Location_Pune,Fuel_Type_CNG,Fuel_Type_Diesel,Fuel_Type_Electric,Fuel_Type_LPG,Fuel_Type_Petrol,Transmission_Automatic,Transmission_Manual
0,8.873984,2012,56000,2,20.8,900,56.53,5,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0

In [95]:
new_pred=model.predict(df1)

In [96]:
new_pred

array([2.51520083])